name: 'sensors'
version: '1.0.0'
config-version: 2

profile: 'sensors'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sensors:
    schema: dbt
    database: sensors
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

vars:
  timezone: 'UTC'